name: curve_sign_design
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.3.0
  - attrs=21.2.0
  - autopep8=1.5.7
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - boost-cpp=1.74.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2021.5.30
  - cairo=1.16.0
  - certifi=2021.5.30
  - cffi=1.14.5
  - cfitsio=3.470
  - chardet=4.0.0
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorama=0.4.4
  - contextily=1.1.0
  - cryptography=3.4.7
  - curl=7.77.0
  - cycler=0.10.0
  - debugpy=1.3.0
  - decorator=5.0.9
  - expat=2.4.1
  - fiona=1.8.20
  - fontconfig=2.13.1
  - freetype=2.10.4
  - freexl=1.0.6
  - gdal=3.2.2
  - geographiclib=1.52
  - geopandas=0.9.0
  - geopy=2.1.0
  - geos=3.9.1
  - geotiff=1.6.0
  - gettext=0.19.8.1
  - hdf4=4.2.15
  - hdf5=1.10.6
  - icu=68.1
  - idna=2.10
  - intel-openmp=2021.2.0
  - ipykernel=6.0.1
  - ipython=7.25.0
  - ipython_genutils=0.2.0
  - jbig=2.1
  - jedi=0.18.0
  - joblib=1.0.1
  - jpeg=9d
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - kealib=1.4.14
  - kiwisolver=1.3.1
  - krb5=1.19.1
  - lcms2=2.12
  - lerc=2.2.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.77.0
  - libdeflate=1.7
  - libffi=3.3
  - libgdal=3.2.2
  - libglib=2.68.2
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.8.0
  - libpng=1.6.37
  - libpq=13.3
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libssh2=1.9.0
  - libtiff=4.3.0
  - libwebp-base=1.2.0
  - libxml2=2.9.12
  - libzip=1.7.3
  - lz4-c=1.9.3
  - matplotlib-base=3.4.2
  - matplotlib-inline=0.1.2
  - mercantile=1.2.1
  - mkl=2021.2.0
  - munch=2.5.0
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - pandas=1.2.4
  - parso=0.8.2
  - pcre=8.44
  - pickleshare=0.7.5
  - pip=21.1.2
  - pixman=0.40.0
  - poppler=21.03.0
  - poppler-data=0.4.10
  - postgresql=13.3
  - proj=8.0.1
  - prompt-toolkit=3.0.19
  - pycodestyle=2.7.0
  - pycparser=2.20
  - pygments=2.9.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyproj=3.1.0
  - pysocks=1.7.1
  - python=3.9.4
  - python-dateutil=2.8.1
  - python_abi=3.9
  - pytz=2021.1
  - pywin32=300
  - pyzmq=22.1.0
  - rasterio=1.2.6
  - requests=2.25.1
  - rtree=0.9.7
  - setuptools=49.6.0
  - shapely=1.7.1
  - six=1.16.0
  - snuggs=1.4.7
  - sqlite=3.35.5
  - tbb=2021.2.0
  - tiledb=2.2.9
  - tk=8.6.10
  - toml=0.10.2
  - tornado=6.1
  - traitlets=5.0.5
  - tzdata=2021a
  - urllib3=1.26.6
  - vc=14.2
  - vs2015_runtime=14.28.29325
  - wcwidth=0.2.5
  - wheel=0.36.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xerces-c=3.2.3
  - xz=5.2.5
  - zeromq=4.3.4
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - argon2-cffi==20.1.0
    - async-generator==1.10
    - bleach==3.3.0
    - defusedxml==0.7.1
    - entrypoints==0.3
    - et-xmlfile==1.1.0
    - ipympl==0.7.0
    - ipywidgets==7.6.3
    - jinja2==3.0.1
    - jsonschema==3.2.0
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.0
    - markupsafe==2.0.1
    - mistune==0.8.4
    - nbclient==0.5.3
    - nbconvert==6.1.0
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - notebook==6.4.0
    - numpy==1.21.1
    - openpyxl==3.0.7
    - packaging==21.0
    - pandocfilters==1.4.3
    - pillow==8.2.0
    - prometheus-client==0.11.0
    - pyrsistent==0.18.0
    - pywinpty==1.1.3
    - scipy==1.6.3
    - seaborn==0.11.1
    - send2trash==1.7.1
    - terminado==0.10.1
    - testpath==0.5.0
    - tqdm==4.62.2
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
    - xlrd==2.0.1
